/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayPinRouteImport } from './routes/play.$pin'
import { Route as JoinPinRouteImport } from './routes/join.$pin'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedResultsSessionIdRouteImport } from './routes/_authenticated/results.$sessionId'
import { Route as AuthenticatedQuizzesNewRouteImport } from './routes/_authenticated/quizzes.new'
import { Route as AuthenticatedHostSessionIdRouteImport } from './routes/_authenticated/host.$sessionId'
import { Route as AuthenticatedQuizzesIdEditRouteImport } from './routes/_authenticated/quizzes.$id.edit'

const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
})
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
})
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const PlayPinRoute = PlayPinRouteImport.update({
  id: '/play/$pin',
  path: '/play/$pin',
  getParentRoute: () => rootRouteImport,
})
const JoinPinRoute = JoinPinRouteImport.update({
  id: '/join/$pin',
  path: '/join/$pin',
  getParentRoute: () => rootRouteImport,
})
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
})
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
})
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
})
const AuthenticatedResultsSessionIdRoute =
  AuthenticatedResultsSessionIdRouteImport.update({
    id: '/results/$sessionId',
    path: '/results/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedQuizzesNewRoute = AuthenticatedQuizzesNewRouteImport.update({
  id: '/quizzes/new',
  path: '/quizzes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
})
const AuthenticatedHostSessionIdRoute =
  AuthenticatedHostSessionIdRouteImport.update({
    id: '/host/$sessionId',
    path: '/host/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  })
const AuthenticatedQuizzesIdEditRoute =
  AuthenticatedQuizzesIdEditRouteImport.update({
    id: '/quizzes/$id/edit',
    path: '/quizzes/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  })

const AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
  AuthenticatedHostSessionIdRoute: AuthenticatedHostSessionIdRoute,
  AuthenticatedQuizzesNewRoute: AuthenticatedQuizzesNewRoute,
  AuthenticatedResultsSessionIdRoute: AuthenticatedResultsSessionIdRoute,
  AuthenticatedQuizzesIdEditRoute: AuthenticatedQuizzesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FoundersRoute: FoundersRoute,
  JoinPinRoute: JoinPinRoute,
  PlayPinRoute: PlayPinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()


